#!user/bin/python
# -*- coding: utf-8 -*-

from __future__ import print_function
from abc import ABCMeta
from abc import abstractmethod

import datetime
import queue

import numpy as np
import pandas as pd

from event import signal_event


class strategy(object):
  """
  Generates signal objects for particular symbols based on the inputs of bars
  generated by a data handler object. Obtains bars from a queue object. All
  functions and actions are defined inside sub-classes (one for each of the
  strategies).
  """
  __metaclass__ = ABCMeta

  @abstractmethod
  def calculate_signals(self):
    raise NotImplementedError("Implement caclulate_signals()")